language: node_js
services:
- mongodb
node_js:
- '8'
before_deploy:
- yarn run build
- npm version $TRAVIS_TAG --allow-same-version=true --git-tag-version=false
deploy:
  provider: npm
  email: contact@louisbodart.fr
  api_key:
    secure: g0l8YnOfb3Awg/m7P/qZQ4xCYeh7C7cgdUAgOuum0RmN9mDM9vEoBsn+ybVG7bqSSNZ9acMgKRzTTk4xNwDywQAPeFRrFZOclQ5i9ngi1KZqQgm66CCtqV3lwryVUwKquH4IZibIrku3V5AxLuBknXms/zxV0qJShrFki4i0nZ9spsmpEp8Qu5BWVOH8iZkxz785I5LHyLzPcBxsTAzKCx94tCppgPPdCDt2cBVTHQXSZvbGEUDR4wSrUbBzNVMplcFl2YSJb89IBaLJMeRj3N4EIOSjetu8ifIahjEq8A0uwuhJxqQqXTCaxL7qC5lqpQe4TgChGXYHkBgyqvhgtzLK/Jl7AQOs9oE4EKDZTLd0Pw6xefPhqVY1OulqXkNNAKJeW460hfQKH8PO4IwebJ4Zwe/y9SyljHPwxqij5HGGHZqlbHhk6SalP0wAKd7bYY7OW8S5VaI74kdFfuYr6ahQBxfTtGYoPLBmqNrmrBVrCBjK48JcWX/4H1xpjtRGGrznrUF60MH4wXhJO0Q1kgM+gz9EXCafx+oRsx6qI39Sxd/awripsMtDHlZd0lgIj20hel5UkiG+q3fmMzsxILTzbn8arxzlobwRBVtWZKFGwxlA50weZkIaSb0WzyblX2raVZD+yu7umC0AiWGvVMkCBsZBgGYkivC46rCcneQ=
  on:
    branch: master
    tags: true
    repo: codeinbrain/honey-pager
  skip_cleanup: true
  verbose: true
